!===================================================
! DO NOT EDIT THIS FILE, it was generated using /glade/u/home/milroy/cesm/cesm1_3_beta11/tools/cprnc/genf90/genf90.pl 
! Any changes you make to this file may be lost
!===================================================

!>
!! @file 
!! $Revision: 751 $
!! $LastChangedDate: 2013-04-02 10:01:13 -0600 (Tue, 02 Apr 2013) $
!! @brief Internal allocation routines for PIO
!<
module alloc_mod

  use pio_kinds
  use pio_types
  use pio_support, only : piodie, CheckMPIreturn, debug
  implicit none
  private

!>
!! @private
!! PIO internal memory allocation check routines.  
!<
  public:: alloc_check
!>
!! @private
!! PIO internal memory allocation check routines.  
!<
  public:: dealloc_check 

  interface alloc_check
     ! TYPE long,int,real,double ! DIMS 1,2
     module procedure alloc_check_1d_long 
     ! TYPE long,int,real,double ! DIMS 1,2
     module procedure alloc_check_2d_long 
     ! TYPE long,int,real,double ! DIMS 1,2
     module procedure alloc_check_1d_int 
     ! TYPE long,int,real,double ! DIMS 1,2
     module procedure alloc_check_2d_int 
     ! TYPE long,int,real,double ! DIMS 1,2
     module procedure alloc_check_1d_real 
     ! TYPE long,int,real,double ! DIMS 1,2
     module procedure alloc_check_2d_real 
     ! TYPE long,int,real,double ! DIMS 1,2
     module procedure alloc_check_1d_double 
     ! TYPE long,int,real,double ! DIMS 1,2
     module procedure alloc_check_2d_double 
     ! TYPE double,long,int,real
     module procedure alloc_check_0d_double
     ! TYPE double,long,int,real
     module procedure alloc_check_0d_long
     ! TYPE double,long,int,real
     module procedure alloc_check_0d_int
     ! TYPE double,long,int,real
     module procedure alloc_check_0d_real
 end interface


  interface dealloc_check
     ! TYPE long,int,real,double ! DIMS 1,2
     module procedure dealloc_check_1d_long
     ! TYPE long,int,real,double ! DIMS 1,2
     module procedure dealloc_check_2d_long
     ! TYPE long,int,real,double ! DIMS 1,2
     module procedure dealloc_check_1d_int
     ! TYPE long,int,real,double ! DIMS 1,2
     module procedure dealloc_check_2d_int
     ! TYPE long,int,real,double ! DIMS 1,2
     module procedure dealloc_check_1d_real
     ! TYPE long,int,real,double ! DIMS 1,2
     module procedure dealloc_check_2d_real
     ! TYPE long,int,real,double ! DIMS 1,2
     module procedure dealloc_check_1d_double
     ! TYPE long,int,real,double ! DIMS 1,2
     module procedure dealloc_check_2d_double
     ! TYPE double,long,int,real
     module procedure dealloc_check_0d_double
     ! TYPE double,long,int,real
     module procedure dealloc_check_0d_long
     ! TYPE double,long,int,real
     module procedure dealloc_check_0d_int
     ! TYPE double,long,int,real
     module procedure dealloc_check_0d_real
  end interface


!>
!! @private
!! PIO internal memory allocation check routines.  
!<
  public :: alloc_print_usage

!>
!! @private
!! PIO internal memory allocation check routines.  
!<
  public :: alloc_trace_on

!>
!! @private
!! PIO internal memory allocation check routines.  
!<
  public :: alloc_trace_off

  character(len=*), parameter :: modName='pio::alloc_mod'

contains

  !
  ! Instantiate all the variations of alloc_check_ and dealloc_check_
  !

  ! TYPE long,int,real,double 
  subroutine alloc_check_1d_long (data,varlen,msg)

    integer(i8), pointer :: data(:)
    integer, intent(in) :: varlen
    character(len=*), intent(in), optional:: msg

    character(len=*), parameter :: subName=modName//'::alloc_check_1d_long'

    integer ierr, ierror, rank

    if(varlen==0) then
      allocate(data(1),stat=ierr)
    else
      allocate(data(varlen),stat=ierr)
    endif
    if (ierr /= 0) then
       if (present(msg)) then
          call piodie('alloc_check_1d_long',96,'allocate failed on task:',&
            msg2=msg)
       else
          call piodie('alloc_check_1d_long',99,'allocate failed on task:')
       endif
    endif

  end subroutine alloc_check_1d_long
  ! TYPE long,int,real,double 
  subroutine alloc_check_1d_int (data,varlen,msg)

    integer(i4), pointer :: data(:)
    integer, intent(in) :: varlen
    character(len=*), intent(in), optional:: msg

    character(len=*), parameter :: subName=modName//'::alloc_check_1d_int'

    integer ierr, ierror, rank

    if(varlen==0) then
      allocate(data(1),stat=ierr)
    else
      allocate(data(varlen),stat=ierr)
    endif
    if (ierr /= 0) then
       if (present(msg)) then
          call piodie('alloc_check_1d_int',96,'allocate failed on task:',&
            msg2=msg)
       else
          call piodie('alloc_check_1d_int',99,'allocate failed on task:')
       endif
    endif

  end subroutine alloc_check_1d_int
  ! TYPE long,int,real,double 
  subroutine alloc_check_1d_real (data,varlen,msg)

    real(r4), pointer :: data(:)
    integer, intent(in) :: varlen
    character(len=*), intent(in), optional:: msg

    character(len=*), parameter :: subName=modName//'::alloc_check_1d_real'

    integer ierr, ierror, rank

    if(varlen==0) then
      allocate(data(1),stat=ierr)
    else
      allocate(data(varlen),stat=ierr)
    endif
    if (ierr /= 0) then
       if (present(msg)) then
          call piodie('alloc_check_1d_real',96,'allocate failed on task:',&
            msg2=msg)
       else
          call piodie('alloc_check_1d_real',99,'allocate failed on task:')
       endif
    endif

  end subroutine alloc_check_1d_real
  ! TYPE long,int,real,double 
  subroutine alloc_check_1d_double (data,varlen,msg)

    real(r8), pointer :: data(:)
    integer, intent(in) :: varlen
    character(len=*), intent(in), optional:: msg

    character(len=*), parameter :: subName=modName//'::alloc_check_1d_double'

    integer ierr, ierror, rank

    if(varlen==0) then
      allocate(data(1),stat=ierr)
    else
      allocate(data(varlen),stat=ierr)
    endif
    if (ierr /= 0) then
       if (present(msg)) then
          call piodie('alloc_check_1d_double',96,'allocate failed on task:',&
            msg2=msg)
       else
          call piodie('alloc_check_1d_double',99,'allocate failed on task:')
       endif
    endif

  end subroutine alloc_check_1d_double

  ! TYPE long,int,real,double 
  subroutine alloc_check_2d_long (data,size1, size2,msg)

    integer(i8), pointer :: data(:,:)
    integer, intent(in) :: size1, size2
    character(len=*), intent(in), optional:: msg

    character(len=*), parameter :: subName=modName//'::alloc_check_2d_long'
    integer ierr, ierror, rank

    allocate(data(size1,size2),stat=ierr)

    if (ierr /= 0) then
       if (present(msg)) then
          call piodie('alloc_check_2d_long',119,'allocate failed on task:',&
            msg2=msg)
       else
          call piodie('alloc_check_2d_long',122,'allocate failed on task:')
       endif
    endif

  end subroutine alloc_check_2d_long
  ! TYPE long,int,real,double 
  subroutine alloc_check_2d_int (data,size1, size2,msg)

    integer(i4), pointer :: data(:,:)
    integer, intent(in) :: size1, size2
    character(len=*), intent(in), optional:: msg

    character(len=*), parameter :: subName=modName//'::alloc_check_2d_int'
    integer ierr, ierror, rank

    allocate(data(size1,size2),stat=ierr)

    if (ierr /= 0) then
       if (present(msg)) then
          call piodie('alloc_check_2d_int',119,'allocate failed on task:',&
            msg2=msg)
       else
          call piodie('alloc_check_2d_int',122,'allocate failed on task:')
       endif
    endif

  end subroutine alloc_check_2d_int
  ! TYPE long,int,real,double 
  subroutine alloc_check_2d_real (data,size1, size2,msg)

    real(r4), pointer :: data(:,:)
    integer, intent(in) :: size1, size2
    character(len=*), intent(in), optional:: msg

    character(len=*), parameter :: subName=modName//'::alloc_check_2d_real'
    integer ierr, ierror, rank

    allocate(data(size1,size2),stat=ierr)

    if (ierr /= 0) then
       if (present(msg)) then
          call piodie('alloc_check_2d_real',119,'allocate failed on task:',&
            msg2=msg)
       else
          call piodie('alloc_check_2d_real',122,'allocate failed on task:')
       endif
    endif

  end subroutine alloc_check_2d_real
  ! TYPE long,int,real,double 
  subroutine alloc_check_2d_double (data,size1, size2,msg)

    real(r8), pointer :: data(:,:)
    integer, intent(in) :: size1, size2
    character(len=*), intent(in), optional:: msg

    character(len=*), parameter :: subName=modName//'::alloc_check_2d_double'
    integer ierr, ierror, rank

    allocate(data(size1,size2),stat=ierr)

    if (ierr /= 0) then
       if (present(msg)) then
          call piodie('alloc_check_2d_double',119,'allocate failed on task:',&
            msg2=msg)
       else
          call piodie('alloc_check_2d_double',122,'allocate failed on task:')
       endif
    endif

  end subroutine alloc_check_2d_double

  !
  !
  !
  ! TYPE long,int,real,double ! DIMS 1,2
  subroutine dealloc_check_1d_long (data,msg)

    integer(i8), pointer :: data(:)
    character(len=*), intent(in), optional:: msg

    character(len=*), parameter :: subName=modName//'::dealloc_check_1d_long'
    integer ierr, ierror, rank

    deallocate(data,stat=ierr)

    if (ierr /= 0) then
       if (present(msg)) then
          call piodie('dealloc_check_1d_long',153, &
               ': deallocate failed on task:',msg2=msg)
       else
          call piodie('dealloc_check_1d_long',156, &
               ': deallocate failed on task:')
       endif

    endif

  end subroutine dealloc_check_1d_long
  ! TYPE long,int,real,double ! DIMS 1,2
  subroutine dealloc_check_2d_long (data,msg)

    integer(i8), pointer :: data(:,:)
    character(len=*), intent(in), optional:: msg

    character(len=*), parameter :: subName=modName//'::dealloc_check_2d_long'
    integer ierr, ierror, rank

    deallocate(data,stat=ierr)

    if (ierr /= 0) then
       if (present(msg)) then
          call piodie('dealloc_check_2d_long',153, &
               ': deallocate failed on task:',msg2=msg)
       else
          call piodie('dealloc_check_2d_long',156, &
               ': deallocate failed on task:')
       endif

    endif

  end subroutine dealloc_check_2d_long
  ! TYPE long,int,real,double ! DIMS 1,2
  subroutine dealloc_check_1d_int (data,msg)

    integer(i4), pointer :: data(:)
    character(len=*), intent(in), optional:: msg

    character(len=*), parameter :: subName=modName//'::dealloc_check_1d_int'
    integer ierr, ierror, rank

    deallocate(data,stat=ierr)

    if (ierr /= 0) then
       if (present(msg)) then
          call piodie('dealloc_check_1d_int',153, &
               ': deallocate failed on task:',msg2=msg)
       else
          call piodie('dealloc_check_1d_int',156, &
               ': deallocate failed on task:')
       endif

    endif

  end subroutine dealloc_check_1d_int
  ! TYPE long,int,real,double ! DIMS 1,2
  subroutine dealloc_check_2d_int (data,msg)

    integer(i4), pointer :: data(:,:)
    character(len=*), intent(in), optional:: msg

    character(len=*), parameter :: subName=modName//'::dealloc_check_2d_int'
    integer ierr, ierror, rank

    deallocate(data,stat=ierr)

    if (ierr /= 0) then
       if (present(msg)) then
          call piodie('dealloc_check_2d_int',153, &
               ': deallocate failed on task:',msg2=msg)
       else
          call piodie('dealloc_check_2d_int',156, &
               ': deallocate failed on task:')
       endif

    endif

  end subroutine dealloc_check_2d_int
  ! TYPE long,int,real,double ! DIMS 1,2
  subroutine dealloc_check_1d_real (data,msg)

    real(r4), pointer :: data(:)
    character(len=*), intent(in), optional:: msg

    character(len=*), parameter :: subName=modName//'::dealloc_check_1d_real'
    integer ierr, ierror, rank

    deallocate(data,stat=ierr)

    if (ierr /= 0) then
       if (present(msg)) then
          call piodie('dealloc_check_1d_real',153, &
               ': deallocate failed on task:',msg2=msg)
       else
          call piodie('dealloc_check_1d_real',156, &
               ': deallocate failed on task:')
       endif

    endif

  end subroutine dealloc_check_1d_real
  ! TYPE long,int,real,double ! DIMS 1,2
  subroutine dealloc_check_2d_real (data,msg)

    real(r4), pointer :: data(:,:)
    character(len=*), intent(in), optional:: msg

    character(len=*), parameter :: subName=modName//'::dealloc_check_2d_real'
    integer ierr, ierror, rank

    deallocate(data,stat=ierr)

    if (ierr /= 0) then
       if (present(msg)) then
          call piodie('dealloc_check_2d_real',153, &
               ': deallocate failed on task:',msg2=msg)
       else
          call piodie('dealloc_check_2d_real',156, &
               ': deallocate failed on task:')
       endif

    endif

  end subroutine dealloc_check_2d_real
  ! TYPE long,int,real,double ! DIMS 1,2
  subroutine dealloc_check_1d_double (data,msg)

    real(r8), pointer :: data(:)
    character(len=*), intent(in), optional:: msg

    character(len=*), parameter :: subName=modName//'::dealloc_check_1d_double'
    integer ierr, ierror, rank

    deallocate(data,stat=ierr)

    if (ierr /= 0) then
       if (present(msg)) then
          call piodie('dealloc_check_1d_double',153, &
               ': deallocate failed on task:',msg2=msg)
       else
          call piodie('dealloc_check_1d_double',156, &
               ': deallocate failed on task:')
       endif

    endif

  end subroutine dealloc_check_1d_double
  ! TYPE long,int,real,double ! DIMS 1,2
  subroutine dealloc_check_2d_double (data,msg)

    real(r8), pointer :: data(:,:)
    character(len=*), intent(in), optional:: msg

    character(len=*), parameter :: subName=modName//'::dealloc_check_2d_double'
    integer ierr, ierror, rank

    deallocate(data,stat=ierr)

    if (ierr /= 0) then
       if (present(msg)) then
          call piodie('dealloc_check_2d_double',153, &
               ': deallocate failed on task:',msg2=msg)
       else
          call piodie('dealloc_check_2d_double',156, &
               ': deallocate failed on task:')
       endif

    endif

  end subroutine dealloc_check_2d_double

! TYPE long,int,real,double
  subroutine alloc_check_0d_long(data,msg)

  integer(i8), pointer :: data
  character(len=*), intent(in), optional:: msg

  character(len=*), parameter :: subName=modName//'::alloc_check_0d_long'
  integer ierr, ierror, rank

  allocate(data,stat=ierr)

  if (ierr /= 0) then
     if (present(msg)) then
        call piodie('alloc_check_0d_long',177,'allocate failed on task:',&
             msg2=msg)
     else
        call piodie('alloc_check_0d_long',180,'allocate failed on task:')
     endif

  endif

end subroutine alloc_check_0d_long
! TYPE long,int,real,double
  subroutine alloc_check_0d_int(data,msg)

  integer(i4), pointer :: data
  character(len=*), intent(in), optional:: msg

  character(len=*), parameter :: subName=modName//'::alloc_check_0d_int'
  integer ierr, ierror, rank

  allocate(data,stat=ierr)

  if (ierr /= 0) then
     if (present(msg)) then
        call piodie('alloc_check_0d_int',177,'allocate failed on task:',&
             msg2=msg)
     else
        call piodie('alloc_check_0d_int',180,'allocate failed on task:')
     endif

  endif

end subroutine alloc_check_0d_int
! TYPE long,int,real,double
  subroutine alloc_check_0d_real(data,msg)

  real(r4), pointer :: data
  character(len=*), intent(in), optional:: msg

  character(len=*), parameter :: subName=modName//'::alloc_check_0d_real'
  integer ierr, ierror, rank

  allocate(data,stat=ierr)

  if (ierr /= 0) then
     if (present(msg)) then
        call piodie('alloc_check_0d_real',177,'allocate failed on task:',&
             msg2=msg)
     else
        call piodie('alloc_check_0d_real',180,'allocate failed on task:')
     endif

  endif

end subroutine alloc_check_0d_real
! TYPE long,int,real,double
  subroutine alloc_check_0d_double(data,msg)

  real(r8), pointer :: data
  character(len=*), intent(in), optional:: msg

  character(len=*), parameter :: subName=modName//'::alloc_check_0d_double'
  integer ierr, ierror, rank

  allocate(data,stat=ierr)

  if (ierr /= 0) then
     if (present(msg)) then
        call piodie('alloc_check_0d_double',177,'allocate failed on task:',&
             msg2=msg)
     else
        call piodie('alloc_check_0d_double',180,'allocate failed on task:')
     endif

  endif

end subroutine alloc_check_0d_double




! TYPE long,int,real,double
subroutine dealloc_check_0d_long (data,msg)

  integer(i8), pointer :: data
  character(len=*), intent(in), optional:: msg

  character(len=*), parameter :: subName=modName//'::dealloc_check_0d_long'
  integer ierr, ierror, rank

  deallocate(data,stat=ierr)

  if (ierr /= 0) then
       if (present(msg)) then
          call piodie('dealloc_check_0d_long',203, &
               ': deallocate failed on task:',msg2=msg)
       else
          call piodie('dealloc_check_0d_long',206, &
               ': deallocate failed on task:')
       endif

  endif

end subroutine dealloc_check_0d_long
! TYPE long,int,real,double
subroutine dealloc_check_0d_int (data,msg)

  integer(i4), pointer :: data
  character(len=*), intent(in), optional:: msg

  character(len=*), parameter :: subName=modName//'::dealloc_check_0d_int'
  integer ierr, ierror, rank

  deallocate(data,stat=ierr)

  if (ierr /= 0) then
       if (present(msg)) then
          call piodie('dealloc_check_0d_int',203, &
               ': deallocate failed on task:',msg2=msg)
       else
          call piodie('dealloc_check_0d_int',206, &
               ': deallocate failed on task:')
       endif

  endif

end subroutine dealloc_check_0d_int
! TYPE long,int,real,double
subroutine dealloc_check_0d_real (data,msg)

  real(r4), pointer :: data
  character(len=*), intent(in), optional:: msg

  character(len=*), parameter :: subName=modName//'::dealloc_check_0d_real'
  integer ierr, ierror, rank

  deallocate(data,stat=ierr)

  if (ierr /= 0) then
       if (present(msg)) then
          call piodie('dealloc_check_0d_real',203, &
               ': deallocate failed on task:',msg2=msg)
       else
          call piodie('dealloc_check_0d_real',206, &
               ': deallocate failed on task:')
       endif

  endif

end subroutine dealloc_check_0d_real
! TYPE long,int,real,double
subroutine dealloc_check_0d_double (data,msg)

  real(r8), pointer :: data
  character(len=*), intent(in), optional:: msg

  character(len=*), parameter :: subName=modName//'::dealloc_check_0d_double'
  integer ierr, ierror, rank

  deallocate(data,stat=ierr)

  if (ierr /= 0) then
       if (present(msg)) then
          call piodie('dealloc_check_0d_double',203, &
               ': deallocate failed on task:',msg2=msg)
       else
          call piodie('dealloc_check_0d_double',206, &
               ': deallocate failed on task:')
       endif

  endif

end subroutine dealloc_check_0d_double

!>
!! @private
!! @fn alloc_print_usage
!! PIO internal memory allocation check routines.  
!<
  subroutine alloc_print_usage(rank,msg)
    use mpi ! _EXTERNAL

    integer, intent(in) :: rank
    character(len=*), intent(in), optional :: msg

    character(len=*), parameter :: subName=modName//'::alloc_print_usage'
    integer ierr, myrank


  end subroutine alloc_print_usage



  subroutine alloc_trace_on(rank,msg)

    integer, intent(in) :: rank
    character(len=*), intent(in), optional :: msg

    character(len=*), parameter :: subName=modName//'::alloc_trace_on'
    integer ierr, myrank


  end subroutine alloc_trace_on



  subroutine alloc_trace_off(rank,msg)

    integer, intent(in) :: rank
    character(len=*), intent(in), optional :: msg

    character(len=*), parameter :: subName=modName//'::alloc_trace_off'
    integer ierr, myrank


  end subroutine alloc_trace_off


end module alloc_mod
