!===================================================
! DO NOT EDIT THIS FILE, it was generated using /glade/u/home/milroy/cesm/cesm1_3_beta11/tools/cprnc/genf90/genf90.pl 
! Any changes you make to this file may be lost
!===================================================

!>
!! @file 
!! $Revision: 877 $
!! $LastChangedDate: 2013-12-06 12:36:54 -0700 (Fri, 06 Dec 2013) $
!! @brief The MPI-IO direct binary interface to PIO
!<
module iompi_mod
  use pio_kinds, only : i4,r4,r8,log_kind,pio_offset
  use pio_types, only : io_desc_t,file_desc_t,var_desc_t, &
       iotype_pbinary, &
       iotype_direct_pbinary,pio_noerr




  use pio_support
  use alloc_mod, only : alloc_check

  use iso_c_binding, only : c_sizeof  ! _EXTERNAL





  use mpi ! _EXTERNAL


  implicit none
  private




  public :: open_mpiio, create_mpiio, close_mpiio, write_mpiio,read_mpiio




!>
!! @private
!<
  interface write_mpiio
! TYPE int,real,double
       module procedure write_mpiio_int
! TYPE int,real,double
       module procedure write_mpiio_real
! TYPE int,real,double
       module procedure write_mpiio_double
    end interface

    interface read_mpiio
! TYPE int,real,double
       module procedure read_mpiio_int
! TYPE int,real,double
       module procedure read_mpiio_real
! TYPE int,real,double
       module procedure read_mpiio_double
    end interface

character(len=*), parameter :: modName='iompi_mod'

contains 

 integer function close_mpiio(File) result(ierr)

     type (File_desc_t), intent(inout) :: File ! file descriptor

     ! ===================
     !  Local variables
     ! ===================
     character(len=*), parameter :: subName=modName//'::close_mpiio'
     integer    :: amode,iotype

     logical, parameter :: Check = .TRUE.

     ierr = PIO_NOERR
     if(File%iosystem%ioproc) then

        call piodie("iompi_mod.F90",84,'PIO was not built with -DUSEMPIIO')

     end if
 end function close_mpiio

 integer function create_mpiio(File,fname) result(ierr)

     type (File_desc_t), intent(inout) :: File ! file descriptor
     character(len=*), intent(in)      :: fname

     ! ===================
     !  Local variables
     ! ===================
     character(len=*), parameter :: subName=modName//'::create_mpiio'
     integer    :: amode,iotype

     logical, parameter :: Check = .TRUE.
     integer :: ierrl
     call piodie("iompi_mod.F90",127,'PIO was not built with -DUSEMPIIO')
     ierr=0
 end function create_mpiio

 integer function open_mpiio(File,fname, CheckMPI) result(ierr)

     type (File_desc_t), intent(inout) :: File ! file descriptor
     character(len=*),   intent(in)    :: fname
     logical, optional,  intent(in)    :: CheckMPI

     ! ===================
     !  Local variables
     ! ===================
     character(len=*), parameter :: subName=modName//'::open_mpiio'
     integer    :: amode,iotype
     integer    :: ierrl

     logical :: Check = .True.
     call piodie("iompi_mod.F90",171,'PIO was not built with -DUSEMPIIO')
     ierr=0
 end function open_mpiio


! TYPE int,real,double
 integer function write_mpiio_int (File,IOBUF,varDesc, iodesc) result(ierr)
    type (File_desc_t), intent(inout)          :: File     ! file descriptor
    integer(i4), intent(in)                    :: IOBUF(:) ! IO buffer
    type (VAR_desc_t), intent(in)            :: varDesc
    type (IO_desc_t), intent(in)            :: IODesc

    character(len=*), parameter :: subName=modName//'::write_mpiio_int'

    character(len=10) :: datarep
    integer(kind=PIO_OFFSET) :: reclen
    integer(i4)              :: iotype
    integer(kind=pio_offset)              :: glen     ! global length of IO request
    integer(kind=PIO_OFFSET) :: offset   ! local offset

    integer :: fstatus(MPI_STATUS_SIZE)

    integer(i4) :: cnt
    logical, parameter :: Check = .TRUE.
     call piodie("iompi_mod.F90",239,'PIO was not built with -DUSEMPIIO')
     ierr=0

 end function write_mpiio_int
! TYPE int,real,double
 integer function write_mpiio_real (File,IOBUF,varDesc, iodesc) result(ierr)
    type (File_desc_t), intent(inout)          :: File     ! file descriptor
    real(r4), intent(in)                    :: IOBUF(:) ! IO buffer
    type (VAR_desc_t), intent(in)            :: varDesc
    type (IO_desc_t), intent(in)            :: IODesc

    character(len=*), parameter :: subName=modName//'::write_mpiio_real'

    character(len=10) :: datarep
    integer(kind=PIO_OFFSET) :: reclen
    integer(i4)              :: iotype
    integer(kind=pio_offset)              :: glen     ! global length of IO request
    integer(kind=PIO_OFFSET) :: offset   ! local offset

    integer :: fstatus(MPI_STATUS_SIZE)

    integer(i4) :: cnt
    logical, parameter :: Check = .TRUE.
     call piodie("iompi_mod.F90",239,'PIO was not built with -DUSEMPIIO')
     ierr=0

 end function write_mpiio_real
! TYPE int,real,double






 integer function write_mpiio_double (File,IOBUF,varDesc, iodesc) result(ierr)
    type (File_desc_t), intent(inout)          :: File     ! file descriptor
    real(r8), intent(in)                    :: IOBUF(:) ! IO buffer
    type (VAR_desc_t), intent(in)            :: varDesc
    type (IO_desc_t), intent(in)            :: IODesc

    character(len=*), parameter :: subName=modName//'::write_mpiio_double'

    character(len=10) :: datarep
    integer(kind=PIO_OFFSET) :: reclen
    integer(i4)              :: iotype
    integer(kind=pio_offset)              :: glen     ! global length of IO request
    integer(kind=PIO_OFFSET) :: offset   ! local offset

    integer :: fstatus(MPI_STATUS_SIZE)

    integer(i4) :: cnt
    logical, parameter :: Check = .TRUE.
     call piodie("iompi_mod.F90",239,'PIO was not built with -DUSEMPIIO')
     ierr=0

 end function write_mpiio_double

! TYPE int,real,double
 integer function read_mpiio_int (File,IOBUF,varDesc, iodesc) result(ierr)
   
    type (File_desc_t), intent(inout)          :: File     ! file descriptor
    integer(i4), intent(out)                      :: IOBUF(:) ! IO buffer
    type (VAR_desc_t), intent(in)               :: varDesc
    type (IO_desc_t), intent(in)               :: IODesc

    character(len=*), parameter :: subName=modName//'::read_mpiio_int'
    character(len=10) :: datarep
    integer(kind=PIO_OFFSET) :: reclen
    integer(i4) :: iotype
    integer(i4) :: cnt
    integer(kind=pio_offset)                   :: glen     ! global length of IO request

    integer(kind=PIO_OFFSET) :: offset   ! local offset
    integer :: fstatus(MPI_STATUS_SIZE)

    logical, parameter :: Debug = .FALSE.
    logical, parameter :: Check = .TRUE.

     datarep   = 'native'
     iotype    = File%iotype
     glen      = iodesc%glen
     offset    = iodesc%IOmap%start
     call piodie("iompi_mod.F90",310,'PIO was not built with -DUSEMPIIO')
     ierr=0
 end function read_mpiio_int
! TYPE int,real,double
 integer function read_mpiio_real (File,IOBUF,varDesc, iodesc) result(ierr)
   
    type (File_desc_t), intent(inout)          :: File     ! file descriptor
    real(r4), intent(out)                      :: IOBUF(:) ! IO buffer
    type (VAR_desc_t), intent(in)               :: varDesc
    type (IO_desc_t), intent(in)               :: IODesc

    character(len=*), parameter :: subName=modName//'::read_mpiio_real'
    character(len=10) :: datarep
    integer(kind=PIO_OFFSET) :: reclen
    integer(i4) :: iotype
    integer(i4) :: cnt
    integer(kind=pio_offset)                   :: glen     ! global length of IO request

    integer(kind=PIO_OFFSET) :: offset   ! local offset
    integer :: fstatus(MPI_STATUS_SIZE)

    logical, parameter :: Debug = .FALSE.
    logical, parameter :: Check = .TRUE.

     datarep   = 'native'
     iotype    = File%iotype
     glen      = iodesc%glen
     offset    = iodesc%IOmap%start
     call piodie("iompi_mod.F90",310,'PIO was not built with -DUSEMPIIO')
     ierr=0
 end function read_mpiio_real
! TYPE int,real,double
 integer function read_mpiio_double (File,IOBUF,varDesc, iodesc) result(ierr)
   
    type (File_desc_t), intent(inout)          :: File     ! file descriptor
    real(r8), intent(out)                      :: IOBUF(:) ! IO buffer
    type (VAR_desc_t), intent(in)               :: varDesc
    type (IO_desc_t), intent(in)               :: IODesc

    character(len=*), parameter :: subName=modName//'::read_mpiio_double'
    character(len=10) :: datarep
    integer(kind=PIO_OFFSET) :: reclen
    integer(i4) :: iotype
    integer(i4) :: cnt
    integer(kind=pio_offset)                   :: glen     ! global length of IO request

    integer(kind=PIO_OFFSET) :: offset   ! local offset
    integer :: fstatus(MPI_STATUS_SIZE)

    logical, parameter :: Debug = .FALSE.
    logical, parameter :: Check = .TRUE.

     datarep   = 'native'
     iotype    = File%iotype
     glen      = iodesc%glen
     offset    = iodesc%IOmap%start
     call piodie("iompi_mod.F90",310,'PIO was not built with -DUSEMPIIO')
     ierr=0
 end function read_mpiio_double

          
 subroutine Write_FORTRAN_CntrlWord(File,reclen)
           
      type (File_desc_t), intent(inout) :: File
      integer(i4), intent(in) :: reclen
           
      character(len=*), parameter :: subName=modName//'::Write_FORTRAN_CntrlWord'
      character(len=10) :: datarep 
      integer(kind=PIO_OFFSET) :: offset, offset2, glen
      integer(i4) :: ierr

      logical, parameter :: Check = .TRUE.
      integer :: fstatus(MPI_STATUS_SIZE)

    
     call piodie("iompi_mod.F90",353,'PIO was not built with -DUSEMPIIO')

 end subroutine Write_FORTRAN_CntrlWord
!***********************************************************************
 subroutine Read_FORTRAN_CntrlWord(File,reclen)

      type (File_desc_t), intent(inout) :: File
      integer(i4), intent(inout) :: reclen

      character(len=*), parameter :: subName=modName//'::Read_FORTRAN_CntrlWord'
      character(len=10) :: datarep
      integer(kind=PIO_OFFSET) :: offset, offset2, glen
      integer(i4) :: ierr

      logical, parameter :: Check = .TRUE.
      integer :: fstatus(MPI_STATUS_SIZE)
     call piodie("iompi_mod.F90",389,'PIO was not built with -DUSEMPIIO')
 end subroutine Read_FORTRAN_CntrlWord

end module iompi_mod
