!===================================================
! DO NOT EDIT THIS FILE, it was generated using /glade/u/home/milroy/cesm/cesm1_3_beta11/tools/cprnc/genf90/genf90.pl 
! Any changes you make to this file may be lost
!===================================================

!>
!! @file 
!! $Revision: 751 $
!! $LastChangedDate: 2013-04-02 10:01:13 -0600 (Tue, 02 Apr 2013) $
!! @brief Generic interface to the rearrange layer
!<

module rearrange

  use pio_kinds
  use pio_types
  use pio_support
  use box_rearrange






  implicit none
  private
  save

!> 
!! @private
!<
  public :: rearrange_init, &
            rearrange_create, &
            rearrange_comp2io, &
            rearrange_io2comp, &
            rearrange_free

  interface rearrange_init
    module procedure rearrange_init_
  end interface


  interface rearrange_create
    module procedure rearrange_create_box_
  end interface

  interface rearrange_comp2io
    ! TYPE real,double,int
    module procedure rearrange_comp2io_real
    ! TYPE real,double,int
    module procedure rearrange_comp2io_double
    ! TYPE real,double,int
    module procedure rearrange_comp2io_int
  end interface

  interface rearrange_io2comp
    ! TYPE real,double,int
    module procedure rearrange_io2comp_real
    ! TYPE real,double,int
    module procedure rearrange_io2comp_double
    ! TYPE real,double,int
    module procedure rearrange_io2comp_int
  end interface

  interface rearrange_free
    module procedure rearrange_free_
  end interface


contains

! TYPE real,double,int
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! rearrange_comp2io_real
!

  subroutine rearrange_comp2io_real(Iosystem,iodesc,compbuf,iobuf)
    implicit none

    type (Iosystem_desc_t) :: Iosystem
    type (io_desc_t)   :: iodesc
    real(r4), intent(in) ::  compbuf(:)
    real(r4), intent(out) :: iobuf(:)



    call box_rearrange_comp2io(Iosystem,iodesc,size(compbuf), compbuf,size(iobuf), iobuf)


  end subroutine rearrange_comp2io_real
! TYPE real,double,int
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! rearrange_comp2io_double
!

  subroutine rearrange_comp2io_double(Iosystem,iodesc,compbuf,iobuf)
    implicit none

    type (Iosystem_desc_t) :: Iosystem
    type (io_desc_t)   :: iodesc
    real(r8), intent(in) ::  compbuf(:)
    real(r8), intent(out) :: iobuf(:)



    call box_rearrange_comp2io(Iosystem,iodesc,size(compbuf), compbuf,size(iobuf), iobuf)


  end subroutine rearrange_comp2io_double
! TYPE real,double,int
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! rearrange_comp2io_int
!

  subroutine rearrange_comp2io_int(Iosystem,iodesc,compbuf,iobuf)
    implicit none

    type (Iosystem_desc_t) :: Iosystem
    type (io_desc_t)   :: iodesc
    integer(i4), intent(in) ::  compbuf(:)
    integer(i4), intent(out) :: iobuf(:)



    call box_rearrange_comp2io(Iosystem,iodesc,size(compbuf), compbuf,size(iobuf), iobuf)


  end subroutine rearrange_comp2io_int




! TYPE real,double,int
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! rearrange_io2comp_real
!
  subroutine rearrange_io2comp_real (Iosystem,iodesc,iobuf,compbuf)
    implicit none

    type (Iosystem_desc_t) :: Iosystem
    type(io_desc_t) :: iodesc
    real(r4) :: iobuf(:)
    real(r4) ::  compbuf(:)


    call box_rearrange_io2comp(Iosystem,iodesc,size(iobuf),iobuf,size(compbuf),compbuf)


  end subroutine rearrange_io2comp_real
! TYPE real,double,int
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! rearrange_io2comp_double
!
  subroutine rearrange_io2comp_double (Iosystem,iodesc,iobuf,compbuf)
    implicit none

    type (Iosystem_desc_t) :: Iosystem
    type(io_desc_t) :: iodesc
    real(r8) :: iobuf(:)
    real(r8) ::  compbuf(:)


    call box_rearrange_io2comp(Iosystem,iodesc,size(iobuf),iobuf,size(compbuf),compbuf)


  end subroutine rearrange_io2comp_double
! TYPE real,double,int
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! rearrange_io2comp_int
!
  subroutine rearrange_io2comp_int (Iosystem,iodesc,iobuf,compbuf)
    implicit none

    type (Iosystem_desc_t) :: Iosystem
    type(io_desc_t) :: iodesc
    integer(i4) :: iobuf(:)
    integer(i4) ::  compbuf(:)


    call box_rearrange_io2comp(Iosystem,iodesc,size(iobuf),iobuf,size(compbuf),compbuf)


  end subroutine rearrange_io2comp_int


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! rearrange_init
! 
! called from initFile_
!


  subroutine rearrange_init_(Iosystem)
    implicit none

    type (Iosystem_desc_t), intent(inout) :: Iosystem



        ! no general init required for box rearranger

  end subroutine rearrange_init_

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
!  rearrange_create_box_
!
!  called from initDecomp
!


  subroutine rearrange_create_box_(Iosystem,compDOF, &
                               dims,ndims,ioDesc)
    implicit none

    type (Iosystem_desc_t), intent(in) :: Iosystem
    integer (kind=pio_offset), intent(in) :: compDOF(:)
    integer, intent(in) :: dims(:)
    integer, intent(in) :: ndims
    type (IO_desc_t) :: ioDesc
    

    if (Iosystem%rearr /= PIO_rearr_box) then
      call piodie( "rearrange.F90",159, &
           'rearrange_create called with args for box but rearranger type is not box, Iosystem%rearr=',&
           Iosystem%rearr)
    endif


    call box_rearrange_create( Iosystem,compDOF,dims,ndims,Iosystem%num_iotasks,ioDesc)



  end subroutine rearrange_create_box_




!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! rearrange_free_
!
! called from freeDecomp


  subroutine rearrange_free_(Iosystem,ioDesc)
    implicit none

    type (Iosystem_desc_t), intent(in) :: Iosystem
    type (IO_desc_t)                   :: ioDesc


    select case (Iosystem%rearr)
    case (PIO_rearr_box)
       call box_rearrange_free(Iosystem,ioDesc)
    case (PIO_rearr_none)
        ! do nothing 

    case default
       call piodie("rearrange.F90",198,'Unrecognized rearranger:',Iosystem%rearr)

    end select


  end subroutine rearrange_free_


end module rearrange
